### ISSUE TITLE
Cannot find wordnet_3.1+.db

### ISSUE THREAD

**Issue by kotu88** [jmccrae/wn-rdf#7]
How to obtain this file: wordnet_3.1+.db ?

I tried to reconstruct it from the available RDF file provided [here](http://wordnet-rdf.princeton.edu/wn31.nt.gz) using WNFromRDF.py but it throws a lot of errors (the format of links has changed a little probably)...

**Comment by jmccrae** [comment]
I can email you a database if needed but you should be able to reconstruct it using the WNFromRDF script now

**Comment by KoconJan** [comment]
It would be great to get this database from you.

Btw. Is line 246 in WNFromRDF.py necessary:
+ print(target) ?

Best,
  Jan

2017-08-04 15:20 GMT+02:00 John McCrae <notifications@github.com>:

**Comment by jmccrae** [comment]
Hi,

You can download the database from

http://john.mccr.ae/wordnet_3.1+.db

Regards,
John
