### ISSUE TITLE
attempt to add language "nld" in wordnet 3.1 rdf failed

### ISSUE THREAD

**Issue by ghost** [jmccrae/wn-rdf#8]
@jmccrae 

Hi,

**purpose:**

- I am trying to add the dutch language ("nld") to wordnet, although only 69% coverage I want to have it

**procedure:**
- cloning repo
`git clone https://github.com/jmccrae/wn-rdf.git`
- getting dependencies: 
```
cd ~/wn-rdf
wget http://john.mccr.ae/wordnet_3.1+.db # see https://github.com/jmccrae/wn-rdf/issues/7
wget https://github.com/jrvosse/wordnet-3.0-rdf/raw/master/rdf/rdf/wn31.nt.gz
cd ~/wn-rdf/mapping
wget http://compling.hss.ntu.edu.sg/omw/all.zip
wget http://verbs.colorado.edu/verb-index/vn/verbnet-3.2.tar.gz
```
- edited omwn.py added line "('nld','nld'): 'nld'" instead of "('cmn','cmn'): 'zho'," ; and removed all others (there seemed to be an issue on cmm as the "tab" file was not there; and scripts are doing inserts thus focussing on "nld" only
- changed "cursor.execute("select wn31 from wn31 where wn30=?",(synsetid,))", to "cursor.execute("select wn31 from wn30 where wn30=?",(synsetid,))", see below
```
cd mapping
sqlite3 mapping.db < mapping31.sql
python omwn.py > omwn.nt 2> omwn.nt.err
grep @nld omwn.nt | wc -l # 60221
grep nld omwn.nt.err |wc -l # 105 rejects for nld
cat omwn.nt | python ../WNFromRDF.py > omwn.sql
grep "@nld" omwn.sql | wc -l # 60221
sqlite3 ../wordnet_3.1+.db < omwn.sql
cd ~/wn-rdf
rm wordnet.nt
python WNRDF.py
grep "@nld" wordnet.nt | wc -l # 0 issue with matching TBD
```

**observations:**

- I notice in following a table wn31 is not created

`https://github.com/jmccrae/wn-rdf/blob/master/mapping/mapping.sql`

- I notice in following that wn31 is used:

```
https://github.com/jmccrae/wn-rdf/blob/master/mapping/omwn.py
https://github.com/jmccrae/wn-rdf/blob/master/mapping/uby.py
```

- in above procedure "@nld" content is created in "omwn.nt", "omwn.sql" but not in "wordnet.nt"
  I assume it had to do with the attempt to use table "wn30" instead of "wn31".

**question**

- would you like to have a look at the workflow I derived above and determine if it would be sufficient to add one language (here "nld"), are other steps needed for that as a dependency, if so please provide some pointers if possible
- would you like to have a look at "mapping.sql" and the definition of table "wn31"
- would you have a look at the the discrepancy between "mapping.sql" and "omwn.py" in terms of the table "wn31"

Thanks in advance,
Bart,

**Comment by jmccrae** [comment]
Hi, I am not sure quite what you are trying to do here, but it seems beyond the scope of this repo. If you would like to chat on Skype about this, maybe we can find something more suitable than this old code. You can contact me at john@mccr.ae
